services:
  web1:
    build: .
    expose:
      - 22
    networks:
      - ansible_net
    container_name: web1

  web2:
    build: .
    expose:
      - 22
    networks:
      - ansible_net
    container_name: web2


  control:
    image: python:3.11-slim
    working_dir: /work
    volumes:
      - ./control:/work
    networks:
      - ansible_net
    container_name: control
    stdin_open: true
    tty: true
    command: >
      bash -c "apt-get update && apt-get install -y sshpass curl && pip install ansible && bash"

  loadbalancer:
    build: .
    networks:
      - ansible_net
    container_name: loadbalancer

networks:
  ansible_net:
    
  