---
- hosts: web
  become: yes
  roles:
    - web
    - hardening
    - node_exporter
        
- hosts: loadBalancer
  become: yes
  roles:
    - loadBalancer
    - hardening
    - node_exporter

- hosts: db 
  become: yes
  vars_files:
    - roles/db/vars/vault.yml 
  roles:
    - db
    - hardening
    - node_exporter

- hosts: monitoring
  become: yes
  vars_files:
    - roles/monitoring/vars/vault.yml 
  roles:
    - monitoring
    - hardening
    - node_exporter