---
- hosts: web
  become: yes
  roles:
    - web
    - hardening
        
- hosts: loadBalancer
  become: yes
  roles:
    - loadBalancer
    - hardening

- hosts: db 
  become: yes
  vars_files:
    - roles/db/vars/vault.yml 
  roles:
    - db
    - hardening