name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Build and start services 
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: sleep 10

      - name: Check container status
        run: docker compose ps

      - name: Ping other nodes fron control container
        run: docker exec control ansible targets -i inventory.ini -m ping

      - name: show logs if failed
        if: failure()
        run: docker compose logs

      - name: Tear down
        if: always()
        run: docker compose down
